name: setup-release-branches.yml
on:
  workflow_dispatch:
    inputs:
      date:
        description: "リリース日を入力"
        required: true
        default: "20240410"
      suffix:
        description: "サフィックスを入力"
        required: true
        default: "a"

jobs:
  validate_release-date_and_suffix:
    runs-on: ubuntu-latest
    env:
      RELEASE_DATE: ${{ github.event.inputs.date }}
      SUFFIX: ${{github.event.inputs.suffix}}
      RELEASE_BRANCH_NAME: release-${{ github.event.inputs.date }}
    steps:
      - name: release_date_and_suffix
        run: |
          echo "ワークフローを実行しているOSは${{ runner.os }}"
          echo "ブランチ名は$RELEASE_BRANCH_NAME"
          if ! [[ "$RELEASE_DATE" =~ ^[0-9]{8}$ ]]; then
              echo "起動を終了します"
              exit 1
          fi
          if ! [[ "$SUFFIX" =~ ^[a-z]$ ]]; then
              echo "起動を終了します"
              exit 1
          fi
          echo "releaseブランチを作成します"
  release-branch:
    needs: validate_release-date_and_suffix
    runs-on: ubuntu-latest
    env:
      RELEASE_BRANCH_NAME: release-${{ github.event.inputs.date }}
    steps:
      - uses: actions/checkout@v4

      - name: create_release-branch
        run: |
          git pull origin master
          git branch $RELEASE_BRANCH_NAME origin/master
          git checkout $RELEASE_BRANCH_NAME
          git push origin $RELEASE_BRANCH_NAME
  release-settings-branch:
    needs: release-branch
    runs-on: ubuntu-latest
    env:
      RELEASE_SETTINGS_BRANCH_NAME: release-settings/${{ github.event.inputs.date }}
    steps:
      - uses: actions/checkout@v4

      - name: create_release-settings-branch
        run: |
          git pull origin master
          git branch $RELEASE_SETTINGS_BRANCH_NAME origin/master
          git checkout $RELEASE_SETTINGS_BRANCH_NAME

      - name: replace_file_parameters
        run: |
          sed s/20240401a/00000000b/ intro.txt
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git push origin $RELEASE_SETTINGS_BRANCH_NAME

  create_pull-request:
    needs: release-settings-branch
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      RELEASE_BRANCH_NAME: release-${{ github.event.inputs.date }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
