name: setup-release-branches.yml
on:
  workflow_dispatch:
    inputs:
      date:
        description: "リリース日とサフィックスを入力"
        required: true
        default: "20240530a"

jobs:
  release-date_and_suffix:
    runs-on: ubuntu-latest
    env:
      GITHUB_EVENT_RELEASE_DATE_AND_SUFFIX: ${{ github.event.inputs.date }}
      RELEASE_DATE_AND_SUFFIX: ${{ inputs.date }}
    steps:
      - name: release_date_and_suffix
        run: echo "入力値は$RELEASE_DATE_AND_SUFFIX"

      - name: release_date
        run: echo "Hello World!"

      - name: suffix
        run: echo "Helloworld!2"

  release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: create_release-branch
        run: git checkout -b release/$RELEASE_DATE_AND_SUFFIX origin/master
