name: setup-release-branches.yml
on:
  workflow_dispatch:
    inputs:
      date:
        description: "リリース日とサフィックスを入力"
        required: true
        default: "20240530a"

jobs:
  release-date_and_suffix:
    runs-on: ubuntu-latest
    env:
      RELEASE_BRANCH_NAME: release-${{ github.event.inputs.date }}
    steps:
      - name: release_date_and_suffix
        run: |
          echo "入力値は$RELEASE_BRANCH_NAME"
          if ! [[ "$RELEASE_BRANCH_NAME" =~ ^release-[0-9]{8}[a-z]$ ]]; then
              echo "起動を終了します"
              exit 1
          fi
          echo "releaseブランチを作成します"

  release-branch:
    runs-on: ubuntu-latest
    env:
      RELEASE_BRANCH_NAME: release-${{ github.event.inputs.date }}
    steps:
      - uses: actions/checkout@v4

      - name: create_release-branch
        run: |
          git pull origin master
          git branch $RELEASE_BRANCH_NAME origin/master
          git checkout $RELEASE_BRANCH_NAME
          git push origin $RELEASE_BRANCH_NAME

  release-settings-branch:
    runs-on: ubuntu-latest
    env:
      RELEASE_SETTINGS_BRANCH_NAME: release-settings-${{ github.event.inputs.date }}
    steps:
      - uses: actions/checkout@v4

      - name: create_release-settings-branch
        run: |
          git pull origin master
          git branch $RELEASE_SETTINGS_BRANCH_NAME origin/master
          git checkout $RELEASE_SETTINGS_BRANCH_NAME
          git push origin $RELEASE_SETTINGS_BRANCH_NAME

  create_pull-request:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      RELEASE_BRANCH_NAME: release-${{ github.event.inputs.date }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: create_pull-request
        run: |
          PULL_REQUEST_URI=$(gh pr create -B $RELEASE_BRANCH_NAME -t "プルリクエスト作成" -b "")
          echo "PULL_REQUEST_URI=$PULL_REQUEST_URI"
