name: setup-release-branches.yml
on:
  workflow_dispatch:
    inputs:
      date:
        description: "リリース日を入力"
        required: true
        default: "20240501"
      suffix:
        description: "サフィックスを入力"
        required: true
        default: "a"

jobs:
  validate_release-date_and_suffix:
    runs-on: ubuntu-latest
    env:
      RELEASE_DATE: ${{ github.event.inputs.date }}
      SUFFIX: ${{ github.event.inputs.suffix }}
      RELEASE_BRANCH_NAME: release-${{ github.event.inputs.date }}
    steps:
      - name: release_date_and_suffix
        run: |
          echo "ワークフローを実行しているOSは${{ runner.os }}"
          echo "ブランチ名は$RELEASE_BRANCH_NAME"
          if ! [[ "$RELEASE_DATE" =~ ^[0-9]{8}$ ]]; then
              echo "起動を終了します"
              exit 1
          fi
          if ! [[ "$SUFFIX" =~ ^[a-z]$ ]]; then
              echo "起動を終了します"
              exit 1
          fi
          echo "releaseブランチを作成します"

  release-branch:
    needs: validate_release-date_and_suffix
    runs-on: ubuntu-latest
    env:
      RELEASE_BRANCH_NAME: release-${{ github.event.inputs.date }}
    steps:
      - uses: actions/checkout@v4

      - name: create_release-branch
        run: |
          git checkout -b $RELEASE_BRANCH_NAME
          git push origin $RELEASE_BRANCH_NAME

  release-settings-branch:
    needs: release-branch
    runs-on: ubuntu-latest
    env:
      RELEASE_SETTINGS_BRANCH_NAME: release-settings/${{ github.event.inputs.date }}
      PARAMETER_NAME: ${{ github.event.inputs.date }}${{ github.event.inputs.suffix }}
    steps:
      - uses: actions/checkout@v4

      - name: create_release-settings-branch
        run: |
          git checkout ${{ env.RELEASE_BRANCH_NAME }}
          git checkout -b $RELEASE_SETTINGS_BRANCH_NAME
          git push origin $RELEASE_SETTINGS_BRANCH_NAME
      - name: replace_file_parameters_and_commit
        run: |
          sed -E -i "s/[0-9]{8}[a-z]$/${PARAMETER_NAME}/" intro.txt
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add intro.txt
          git commit -m "Update intro.txt with ${PARAMETER_NAME}"
          git push origin $RELEASE_SETTINGS_BRANCH_NAME

  create_pull-request:
    needs: release-settings-branch
    runs-on: ubuntu-latest
    permissions:
      issues: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RELEASE_BRANCH_NAME: release-${{ github.event.inputs.date }}
      RELEASE_SETTINGS_BRANCH_NAME: release-settings/${{ github.event.inputs.date }}
    steps:
      - uses: actions/checkout@v4

      - name: create_pull-request
        run: |
          pr_data=$(jq -n \
          --arg title "リリース設定のプルリクエスト: $RELEASE_SETTINGS_BRANCH_NAME" \
          --arg head "$RELEASE_SETTINGS_BRANCH_NAME" \
          --arg base "$RELEASE_BRANCH_NAME" \
          --arg body "このプルリクエストは${RELEASE_SETTINGS_BRANCH_NAME}から${RELEASE_BRANCH_NAME}への変更を提案します。" \
          '{title: $title, head: $head, base: $base, body: $body}')

          curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/pulls \
              -d "$pr_data"
