name: setup-release-branches.yml
on:
  workflow_dispatch:
    inputs:
      date:
        description: "リリース日とサフィックスを入力"
        required: true
        default: "202405211a"

jobs:
  release-date_and_suffix:
    runs-on: ubuntu-latest
    env:
      RELEASE_DATE: ${{ github.event.inputs.date }}
    steps:
      - name: release_date_and_suffix
        run: echo "入力値は$RELEASE_DATE"

      - name: release_date
        run: echo "Hello World!"

      - name: suffix
        run: echo "Helloworld!2"

  release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: create_release-branch
        run: echo "Hello World!3"

      - name: create_release-branch
        run: echo "Hello World!4"
